# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
- {name: 'Initial Storyboard',    url: 'storyboard'}
- {name: 'The Game',              url: 'details'}
- {name: 'Development',           url: 'development'}
- {name: 'Documentation',         url: 'documentation'}
- {name: 'The Developers',        url: 'about'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
